# Store your OpenAI API key here
OPENAI_API_KEY = "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"
